### ISSUE TITLE
DB_NAME and related variables are deprecated

### ISSUE THREAD

**Issue by hkirsman** [wunderio/silta#1]
They say these variables are deprecated so we should update to something like this:
    
      $lando_info = json_decode(getenv('LANDO_INFO'), TRUE);
      $databases['default']['default'] = [
        'driver' => 'mysql',
        'database' => $lando_info['database']['creds']['database'],
        'username' => $lando_info['database']['creds']['user'],
        'password' => $lando_info['database']['creds']['password'],
        'host' => $lando_info['database']['internal_connection']['host'],
        'port' => $lando_info['database']['internal_connection']['port'],
      ];

https://github.com/lando/lando/issues/585#issuecomment-390949763
https://docs.devwithlando.io/tutorials/lando-info.html

**Comment by tormi** [comment]
This is covered in https://github.com/wunderio/drupal-project/blob/master/web/sites/default/settings.php

**Comment by tormi** [comment]
Reopening because currently silta doesn't use `settings.php` from `wunderio/drupal-project`.

**Comment by Jancis** [comment]
@tormi I believe this is fixed again: https://github.com/wunderio/drupal-project/blob/master/web/sites/default/settings.php#L8

**Comment by tormi** [comment]
@Jancis, what I meant was that this project (`wunderio/silta`) doesn't use `settings.php` from `wunderio/drupal-project` in converting process. Don't know whether it should.

**Comment by Jancis** [comment]
I believe something like this solve the issue -

https://github.com/wunderio/drupal-project/pull/22 + https://github.com/wunderio/silta/pull/3

**Comment by floretan** [comment]
These two PRs have been merged, I think this can be closed.
