### ISSUE TITLE
CircleCI examples invalid config

### ISSUE THREAD

**Issue by dbruvers** [wunderio/silta#47]
**name**
One of the examples mentions [`name: Storybook build & deploy`](https://github.com/wunderio/silta/blob/0d96126d2932a7c27f91d3d8d4408ec38078a82f/docs/circleci-examples.md?plain=1#L75). 

At least on my previous try this seemed to be an invalid option for name. It seems that it needs to be a machine name instead of human readable label. E.g. `storybook-build-deploy` instead of `Storybook build & deploy`.

**silta_config**

In the same example as above, [this line](https://github.com/wunderio/silta/blob/0d96126d2932a7c27f91d3d8d4408ec38078a82f/docs/circleci-examples.md?plain=1#L77) ` silta_config: silta/silta.yml,silta/silta-storybook.yml` causes the error: 
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
simple:
- (root): Additional property php is not allowed
```

Removing the default `silta/silta.yml` config seems to fix the issue:
```
silta_config: silta/silta-storybook.yml
```

**Comment by Jancis** [comment]
i'll take a wild guess and say this was caused by incorrect configuration in `silta/silta-storybook.yml`. Simple chart does not have `php` property in root level (or anywhere), it only applies to drupal chart currently.
