### ISSUE TITLE
Update docs for encrypting configurations

### ISSUE THREAD

**Issue by kirkkala** [wunderio/silta#7]
[Encrypting sensitive configuration](https://github.com/wunderio/silta/blob/master/docs/encrypting_sensitive_configuration.md) documentation could be better for different OS's:

The examples with -pbkdf2 fail on invalid ciphername with OSX. I though got lucky with encrypting like
```
openssl aes-256-cbc -in silta/secrets.dec -out silta/secrets
```
but not sure if that's 100% correct?

OSX Mojave is on openssl version `LibreSSL 2.6.5`

**Comment by floretan** [comment]
I'm checking with Janis to see what are the implications of dropping -pbkdf2. If we go through with this we would also need to re-encrypt the files for existing projects.

**Comment by Jancis** [comment]
We can't drop it anymore, this has been rewritten to golang code and can be used with silta-cli (https://github.com/wunderio/silta-cli/blob/master/docs/silta_secrets_decrypt.md). But again, cli does not work on os/x yet.
